version: '3.8'

services:
  jenkins:
    container_name: my-jenkins-container
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  ngrok:
    image: ngrok/ngrok:latest
    command: ["http", "jenkins:8080", "--authtoken=2wHAi5eELEoZtyYpfDYCjYMiFBE_mEMNX1xB5pPSANHGdVsP"]
    environment:
      - NGROK_HOST=jenkins
      - NGROK_PORT=8080
    ports:
      - "4040:4040"

volumes:
  jenkins_home: